import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/lib/providers";
import Sidenav from "@/components/sidenav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <div>
        <Sidenav />
        <div className="md:ml-[250px] bg-[#FCFCFC]">{children}</div>
      </div>
    </Providers>
  );
}
