import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/lib/providers";
import Sidenav from "@/components/sidenav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      
          <Sidenav />

          <div className="w-full ml-[200px]">
            {children}
          </div>
        
    </Providers>
  );
}
